### ISSUE TITLE
pattern not found, but succeeded

### ISSUE THREAD

**Issue by shinout** [kt3k/ruby-bmp#6]
https://github.com/kt3k/bmp/blob/master/lib/bump/application.rb#L112

here, `exit 1` is not executed.

I think it is more natural that it stops bumping when some files don't match the pattern.

**Comment by kt3k** [comment]
thanks,

I agree we should check that all patterns are available before performing any rewrite of files.

I will add this feature at the next version.

**Comment by shinout** [comment]
thanks!
